services:
  app:
    build: 
      args:
        user: fullStackAdrianoCobuccio
        uid: 1000
      context: .
      dockerfile: Dockerfile
    working_dir: /application
    volumes:
      - ./application:/application
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    networks:
      - adriano_cobuccio_fullstack

  nginx:
    image: nginx:alpine
    ports:
      # - 8000:80
      - "${DOCKER_WEBSERVER_PORT}:80"
    volumes:
      - ./application:/application
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - adriano_cobuccio_fullstack  

  mysql:
    # image: mysql:8.0
    image: mariadb:10.11.5
    restart: always
    environment:
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    volumes:
      - ./docker/mysql/volumes/mysql:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      # - ./docker/mysql/dump/db_fullStackAdrianoCobuccio.sql:/docker-entrypoint-initdb.d/db_fullStackAdrianoCobuccio.sql
    ports:
      # - 3306:3306
      - "${DOCKER_EXTERNAL_MYSQL_PORT}:3306"
    networks:
      - adriano_cobuccio_fullstack

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "${DOCKER_PHP_MY_ADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
      # PMA_USER: root
      PMA_USER: ${DOCKER_MYSQL_USER}
      PMA_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
      UPLOAD_LIMIT: 5G
    depends_on:
      - mysql
    networks:
      - adriano_cobuccio_fullstack

networks:
  adriano_cobuccio_fullstack:
    driver: bridge